name: Bongo separated tests report
description: 'Send bongo report from the artifacts'
inputs:
  artifact:
    description: artifacts(s) to look for files
    required: true
  sdk_name:
    description: name of the reported sdk
    required: true
  report_id:
    description: id which would be used for the report
    required: true
  sandbox:
    description: flag for to send report to the sandbox
    required: false
    default: 'true'

runs:
  using: node16
  main: dist/index.js