name: Tests
description: Run tests for a package
inputs:
  working-directory:
    # Can be on of:
    # eyes_images
    # eyes_playwright
    # eyes_robotframework
    # eyes_selenium
    required: true
    description: package directory
  test-type:
    # Can be one of:
    # functional_tests
    # generated_tests
    # sauce_functional_tests
    # installation_tests
    # unit_tests
    default: all_tests
    required: false
    description: type of the testing
  pytest-filter:
    required: false
    description: grep pattern to filter tests
  core-build-dir:
    required: false
    description: path to core-universal binaries
  bongo-report:
    default: false
    description: send bongo report, without bongo-report-release-package it will be marked as sandbox
  bongo-report-release-package:
    required: false
    description: name of a package being released, bongo report will be marked as prod
runs:
  using: composite
  steps:
    - name: Test
      shell: bash
      env:
        BONGO_REPORT_TESTS: ${{inputs.bongo-report}}
        RELEASING_PACKAGE: ${{inputs.bongo-report-release-package}}
        PYTEST_FILTER: ${{inputs.pytest-filter}}
        USDK_BUILD_DIR: ${{inputs.core-build-dir}}
      run: |
        make --directory=python ${{inputs.working-directory}}_${{inputs.test-type}}
