name: Test

run-name: Test (${{inputs.packages}})

on:
  workflow_dispatch:
    inputs:
      packages:
        description: package names
        type: string
        required: true
      test-type:
        description: testing type (unit, it, e2e)
        type: string
        required: false
      build-type:
        description: build type
        type: string
        required: false
      setup-type:
        description: setup type
        type: string
        required: false
      env:
        description: environment variables
        type: string
        required: false
      grep:
        description: test name pattern
        required: false

env:
  FORCE_COLOR: 3
  DISPLAY: ':99'
  NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  BROWSERSTACK_USERNAME: applitools
  BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
  AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      tests: ${{steps.setup.outputs.tests}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        id: setup
        with:
          type: test
          packages: ${{inputs.packages}}
          env: ${{inputs.env}}

  js-test:
    needs: [setup]
    if: ${{fromJSON(needs.setup.outputs.tests).js}}
    strategy:
      fail-fast: false
      matrix: 
        include: ${{fromJSON(needs.setup.outputs.tests).js}}
    name: Test / ${{matrix.display-name}}
    timeout-minutes: 60
    runs-on: ${{matrix.runner || 'ubuntu-latest'}}
    container: ${{matrix.container}}
    env: ${{matrix.env}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version || 'lts/*'}}
      - name: Yarn cache
        uses: actions/cache@v3
        with:
          path: ./js/.yarn/cache
          key: yarn-cache-${{hashFiles('./js/yarn.lock', '.yarnrc.yml')}}
          restore-keys: yarn-cache-
      - name: Run tests
        uses: ./.github/actions/js/test
        with:
          working-directory: ${{matrix.working-directory}}
          shell: ${{matrix.shell || 'bash'}}
          framework-version: ${{matrix.framework-version}}
          test-type: ${{matrix.test-type || inputs.test-type}}
          build-type: ${{matrix.build-type || inputs.build-type}}
          setup-type: ${{matrix.setup-type || inputs.setup-type}}
          parallel: ${{matrix.parallel}}
          grep: ${{inputs.grep}}
      - name: Save testing artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.name}}
          path: ./logs
          retention-days: 2
          if-no-files-found: ignore

  report:
    needs: [setup, js-test]
    if: (success() || failure()) && fromJSON(needs.setup.outputs.tests).*
    name: Report
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Report
        id: report
        uses: ./.github/actions/report
        with:
          artifact: ${{join(fromJSON(needs.setup.outputs.tests).*.*.key)}}
          path: |
            ./report*.json